### ISSUE TITLE
How to debug SCENE_DOESN'T_EXIST

### ISSUE THREAD

**Issue by alpha0010** [MinaSamir11/react-native-in-app-review#101]
I received a `SCENE_DOESN'T_EXIST` from production error logging.  Do you have any recommendations how I can track down (and fix) what occurred?

**Comment by MinaSamir11** [comment]
if it happened with a user once, you can ignore this, because it comes from iOS of checking app foreground is active. 
it take an instance from ```UIWindowScene``` to launch flow. 

if it's repeated every time with same user, may app with OS behave with unexpected way. which also you can't do something with this issue. 

all you can do it. repeat launch review flow later on, or take this data to analytics tools with user who hasn't review your app due to error occurs at this time, etc

**Comment by alpha0010** [comment]
I have not seen this come up recently, so probably just the foreground check you mention.
