### ISSUE TITLE
Add listener to dialog buttons

### ISSUE THREAD

**Issue by proverbface** [MinaSamir11/react-native-in-app-review#21]
It would be great if there was a way to add a listener from JS to the cancel and submit buttons so that we can know if presenting the dialog should happen later on or never again.

**Comment by MinaSamir11** [comment]
**API Hint:**
_the API does not indicate whether the user reviewed or not, or even whether the review dialog was shown. Thus, no matter the result, we continue our app flow._

**if we add a listener is Successful  if flow has finish even if user closes the review window, will sent is successful true also, because of API, would be useful for you ?**

https://developer.android.com/guide/playcore/in-app-review/kotlin-java#kotlin

**Comment by proverbface** [comment]
Yeah, you're right, looking at the Android documentation it's not possible to tell whether the dialog is shown, the cancel or submit buttons are pressed. Same things with Apple https://developer.apple.com/documentation/storekit/skstorereviewcontroller.

I'm closing this ticket. Good chat and thank you for the quick reply! :)
