### ISSUE TITLE
Quota on Android in production version & method to count the number of requests

### ISSUE THREAD

**Issue by Esoriak** [MinaSamir11/react-native-in-app-review#23]
hi, 

Thank you for this great module.

I didn't understand one thing, in the guideline I am told to use the LaunchReviewFlow method to control the number of appearances, is the InAppReview.RequestInAppReview () contains this method?

I can't be sure that in production version on android a quota will be applied. Will the request appear every time? This is the case in internal testing anyway.

Otherwise, I wanted to know if there was an option to know when the user actually leaves a note. Is there a method for that to know the percentage of requests that were used to obtain a note?

Thanks for your time

**Comment by MinaSamir11** [comment]
Hello @Esoriak 
Thank you for you feedback.

there is no method tell you  number of appearances, but the way of implementation logic is up  to you but you must follow this guideline while calling method. when and how to call it :->

**- To provide a great user experience, Google Play enforces a time-bound quota on how often a user can be shown the review dialog. Because of this quota, calling the launchReviewFlow method more than once during a short period of time (for example, less than a month) might not always display a dialog.**

so when you call method InAppReview.RequestInAppReview ()  it will appear every time but you have to handle calling method, and build your implementation logic to follow guideline ex. you can build your code as following: call method twice in a month in two different of time let say you will call it after 15 days you show review flow to user. 

For more info :->
_the API does not indicate whether the user reviewed or not, or even whether the review dialog was shown. Thus, no matter the result, we continue our app flow._

Finally I have answered all your questions clearly ?
