### ISSUE TITLE
How to know user has given the rating or not 

### ISSUE THREAD

**Issue by aparnagude** [MinaSamir11/react-native-in-app-review#8]
I want to know user has given rating or not. If user already submitted the rating then I don't want to show the popup. Please give me solution for this.

**Comment by imadmk** [comment]
From this [docs](https://developer.android.com/guide/playcore/in-app-review/test) google implicitly says that the popup will (automaticatlly) not shown if the user account already review the app. So no need to implement anything else.

As for a way to know that a user has given any rating or not, until now, there is no way to get that information, maybe because it can be misused for something like force review.

**Comment by MinaSamir11** [comment]
@aparnagude  as Mr. @imadmk said google implicitly triggered UI automatically if the user account not review the app yet. UI will not triggered if user reviewed already app on play store, So you don't need to implement anything else.
